<a href="https://colab.research.google.com/github/midhun2708/EDA-Th/blob/main/21BDS0063.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv('prison.csv')
df.head(10)

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.000077,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.000177,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,-0.000712,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,-0.001318,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,-0.002618,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0
5,6,1,85,0,0.2545,0.6530,0.08908,4.630758,35.266800,1.532721,...,-0.003696,0.001666,-0.02259,-0.029999,0.0042,259.261139,5.557836,0.056297,0,0
6,7,1,86,1,0.2542,0.6572,0.09833,5.665331,37.873497,1.734365,...,-0.004348,0.001230,0.00925,-0.030001,0.0042,270.551239,5.600461,0.042626,0,0
7,8,1,87,0,0.2539,0.6614,0.07775,5.686924,39.581070,1.738170,...,-0.003675,0.000556,-0.02058,-0.030001,0.0042,288.176331,5.663573,0.063111,0,0
8,9,1,88,0,0.2536,0.6656,0.07208,5.728628,41.055916,1.745476,...,-0.002496,-0.000865,-0.00567,-0.029999,0.0042,313.872986,5.748989,0.085416,0,0
9,10,1,89,0,0.2533,0.6698,0.07025,6.036973,41.251614,1.797903,...,-0.001906,-0.001484,-0.00183,-0.030001,0.0042,307.082520,5.727117,-0.021872,0,0

In [44]:
df.tail(5)

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.000770,-0.003921,-0.00025,0.01,0.0143,203.225800,5.314318,0.056648,0,0
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,0.000808,-0.005127,-0.00967,0.01,0.0143,224.017471,5.411724,0.097406,0,0
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,0.003559,-0.005790,-0.00208,0.01,0.0143,244.493393,5.499188,0.087464,0,0
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,0.002855,-0.006668,0.00500,0.01,0.0143,239.956329,5.480457,-0.018732,0,0
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,0.003203,-0.003729,-0.00200,0.01,0.0143,228.602142,5.431983,-0.048474,0,0

In [8]:
df['year'].value_counts()

year
80    51
81    51
82    51
83    51
84    51
85    51
86    51
87    51
88    51
89    51
90    51
91    51
92    51
93    51
Name: count, dtype: int64

In [9]:
df.describe()

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
count,714.000000,714.00000,714.000000,714.00000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,...,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000
mean,357.500000,26.00000,86.500000,0.25070,0.105329,0.641727,0.068487,5.078585,46.435141,1.426112,...,-0.002448,-0.000262,0.000525,0.030098,0.001596,199.980341,5.129948,0.066474,0.008403,0.016807
std,206.258333,14.72992,4.033955,0.43372,0.121210,0.225690,0.022151,3.440078,12.117244,0.654660,...,0.002047,0.003081,0.012399,0.089816,0.003081,132.713456,0.580049,0.066585,0.091348,0.128637
min,1.000000,1.00000,80.000000,0.00000,0.002000,0.153000,0.021420,0.475628,20.965015,-0.743120,...,-0.010630,-0.008652,-0.041840,-0.450005,-0.003500,20.826952,3.036248,-0.214960,0.000000,0.000000
25%,179.250000,13.00000,83.000000,0.00000,0.020250,0.457850,0.053000,2.824363,38.671989,1.038283,...,-0.003680,-0.002845,-0.007000,0.009999,0.000000,113.038683,4.727730,0.024878,0.000000,0.000000
50%,357.500000,26.00000,86.500000,0.00000,0.071000,0.671350,0.066000,4.515549,45.185146,1.507526,...,-0.002491,-0.000067,-0.000790,0.020000,0.000800,172.454063,5.150131,0.064914,0.000000,0.000000
75%,535.750000,39.00000,90.000000,0.75000,0.148075,0.815925,0.080958,6.500603,54.392672,1.871895,...,-0.001178,0.001760,0.008640,0.070000,0.002200,251.896126,5.529016,0.104964,0.000000,0.000000
max,714.000000,51.00000,93.000000,1.00000,0.703000,1.000000,0.180330,29.217993,88.392731,3.374785,...,0.005333,0.010487,0.046580,0.490002,0.014300,1286.837524,7.159943,0.364590,1.000000,1.000000

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
709    False
710    False
711    False
712    False
713    False
Length: 714, dtype: bool

In [11]:
df = df.drop_duplicates()
df

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.000077,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.000177,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,-0.000712,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,-0.001318,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,-0.002618,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.000770,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0,0
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,0.000808,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0,0
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,0.003559,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0,0
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,0.002855,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0,0
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,0.003203,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0,0

In [12]:
df.replace(to_replace =1, value= np.nan)

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,NaN,NaN,80,0.0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.000077,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0.0,0.0
1,2.0,NaN,81,0.0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.000177,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0.0,0.0
2,3.0,NaN,82,NaN,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,-0.000712,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0.0,0.0
3,4.0,NaN,83,0.0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,-0.001318,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0.0,0.0
4,5.0,NaN,84,0.0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,-0.002618,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710.0,51.0,89,0.0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.000770,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0.0,0.0
710,711.0,51.0,90,NaN,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,0.000808,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0.0,0.0
711,712.0,51.0,91,0.0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,0.003559,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0.0,0.0
712,713.0,51.0,92,0.0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,0.002855,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0.0,0.0
713,714.0,51.0,93,0.0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,0.003203,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0.0,0.0

In [13]:
df.replace(to_replace =[1, 51], value= [np.nan, 2])

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,NaN,NaN,80,0.0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.000077,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0.0,0.0
1,2.0,NaN,81,0.0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.000177,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0.0,0.0
2,3.0,NaN,82,NaN,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,-0.000712,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0.0,0.0
3,4.0,NaN,83,0.0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,-0.001318,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0.0,0.0
4,5.0,NaN,84,0.0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,-0.002618,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710.0,2.0,89,0.0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.000770,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0.0,0.0
710,711.0,2.0,90,NaN,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,0.000808,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0.0,0.0
711,712.0,2.0,91,0.0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,0.003559,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0.0,0.0
712,713.0,2.0,92,0.0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,0.002855,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0.0,0.0
713,714.0,2.0,93,0.0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,0.003203,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0.0,0.0

In [14]:
df.isnull()

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
710,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
711,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
712,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
713,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
df.notnull()

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
710,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
711,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
712,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
713,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [16]:
df.isnull().sum()

rownames    0
state       0
year        0
govelec     0
black       0
metro       0
unem        0
criv        0
crip        0
lcriv       0
lcrip       0
gcriv       0
gcrip       0
y81         0
y82         0
y83         0
y84         0
y85         0
y86         0
y87         0
y88         0
y89         0
y90         0
y91         0
y92         0
y93         0
ag0_14      0
ag15_17     0
ag18_24     0
ag25_34     0
incpc       0
polpc       0
gincpc      0
gpolpc      0
cag0_14     0
cag15_17    0
cag18_24    0
cag25_34    0
cunem       0
cblack      0
cmetro      0
pris        0
lpris       0
gpris       0
final1      0
final2      0
dtype: int64

In [17]:
df.isnull().sum().sum()

0

In [18]:
df.count()

rownames    714
state       714
year        714
govelec     714
black       714
metro       714
unem        714
criv        714
crip        714
lcriv       714
lcrip       714
gcriv       714
gcrip       714
y81         714
y82         714
y83         714
y84         714
y85         714
y86         714
y87         714
y88         714
y89         714
y90         714
y91         714
y92         714
y93         714
ag0_14      714
ag15_17     714
ag18_24     714
ag25_34     714
incpc       714
polpc       714
gincpc      714
gpolpc      714
cag0_14     714
cag15_17    714
cag18_24    714
cag25_34    714
cunem       714
cblack      714
cmetro      714
pris        714
lpris       714
gpris       714
final1      714
final2      714
dtype: int64

In [19]:
df['final3'] = np.nan
df

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2,final3
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0,NaN
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0,NaN
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0,NaN
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0,NaN
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0,0,NaN
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0,0,NaN
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0,0,NaN
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0,0,NaN
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0,0,NaN

In [20]:
df.isnull().sum()

rownames      0
state         0
year          0
govelec       0
black         0
metro         0
unem          0
criv          0
crip          0
lcriv         0
lcrip         0
gcriv         0
gcrip         0
y81           0
y82           0
y83           0
y84           0
y85           0
y86           0
y87           0
y88           0
y89           0
y90           0
y91           0
y92           0
y93           0
ag0_14        0
ag15_17       0
ag18_24       0
ag25_34       0
incpc         0
polpc         0
gincpc        0
gpolpc        0
cag0_14       0
cag15_17      0
cag18_24      0
cag25_34      0
cunem         0
cblack        0
cmetro        0
pris          0
lpris         0
gpris         0
final1        0
final2        0
final3      714
dtype: int64

In [21]:
df.isnull().sum().sum()

714

In [22]:
df.dropna()

Empty DataFrame
Columns: [rownames, state, year, govelec, black, metro, unem, criv, crip, lcriv, lcrip, gcriv, gcrip, y81, y82, y83, y84, y85, y86, y87, y88, y89, y90, y91, y92, y93, ag0_14, ag15_17, ag18_24, ag25_34, incpc, polpc, gincpc, gpolpc, cag0_14, cag15_17, cag18_24, cag25_34, cunem, cblack, cmetro, pris, lpris, gpris, final1, final2, final3]
Index: []

[0 rows x 47 columns]

In [23]:
df.dropna(how='all')

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2,final3
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0,NaN
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0,NaN
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0,NaN
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0,NaN
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0,0,NaN
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0,0,NaN
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0,0,NaN
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0,0,NaN
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0,0,NaN

In [24]:
df.dropna(how='all', axis=1)

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.000077,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.000177,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,-0.000712,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,-0.001318,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,-0.002618,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.000770,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0,0
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,0.000808,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0,0
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,0.003559,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0,0
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,0.002855,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0,0
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,0.003203,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0,0

In [25]:
df.dropna(thresh=5, axis=1)

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.000077,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.000177,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,-0.000712,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,-0.001318,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,-0.002618,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.000770,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0,0
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,0.000808,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0,0
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,0.003559,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0,0
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,0.002855,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0,0
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,0.003203,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0,0

In [26]:
ser = df.black
ser.sum()

75.20519996387881

In [27]:
ser.mean()

0.10532941171411599

In [28]:
ser.cumsum()

0       0.2560
1       0.5117
2       0.7671
3       1.0222
4       1.2770
        ...
709    75.1726
710    75.1806
711    75.1887
712    75.1969
713    75.2052
Name: black, Length: 714, dtype: float64

In [29]:
filledDf = df.fillna(0)
filledDf

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2,final3
0,1,1,80,0,0.2560,0.6320,0.08775,4.447868,44.476376,1.492425,...,0.001990,0.01675,-0.059999,0.0002,141.334717,4.951131,-0.020659,0,0,0.0
1,2,1,81,0,0.2557,0.6362,0.10667,4.700944,44.248787,1.547763,...,0.004632,0.01892,-0.030001,0.0042,163.533646,5.097019,0.145888,0,0,0.0
2,3,1,82,1,0.2554,0.6404,0.14367,4.497580,42.050446,1.503539,...,0.000013,0.03700,-0.029999,0.0042,183.694809,5.213276,0.116257,0,0,0.0
3,4,1,83,0,0.2551,0.6446,0.13667,4.186833,37.084393,1.431945,...,0.001163,-0.00700,-0.030001,0.0042,218.624207,5.387354,0.174078,0,0,0.0
4,5,1,84,0,0.2548,0.6488,0.11167,4.353239,35.042255,1.470920,...,0.001297,-0.02500,-0.030001,0.0042,245.068619,5.501538,0.114184,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,51,89,0,0.0079,0.2817,0.06275,2.679039,37.655022,0.985458,...,-0.003921,-0.00025,0.010000,0.0143,203.225800,5.314318,0.056648,0,0,0.0
710,711,51,90,1,0.0080,0.2960,0.05308,3.011013,39.057270,1.102277,...,-0.005127,-0.00967,0.010000,0.0143,224.017471,5.411724,0.097406,0,0,0.0
711,712,51,91,0,0.0081,0.3103,0.05100,3.115721,40.965065,1.136460,...,-0.005790,-0.00208,0.010000,0.0143,244.493393,5.499188,0.087464,0,0,0.0
712,713,51,92,0,0.0082,0.3246,0.05600,3.202151,42.647312,1.163823,...,-0.006668,0.00500,0.010000,0.0143,239.956329,5.480457,-0.018732,0,0,0.0
713,714,51,93,0,0.0083,0.3389,0.05400,2.861702,38.768085,1.051417,...,-0.003729,-0.00200,0.010000,0.0143,228.602142,5.431983,-0.048474,0,0,0.0

In [30]:
df.mean()
filledDf.mean()

rownames      357.500000
state          26.000000
year           86.500000
govelec         0.250700
black           0.105329
metro           0.641727
unem            0.068487
criv            5.078585
crip           46.435141
lcriv           1.426112
lcrip           3.803649
gcriv           0.019184
gcrip          -0.003045
y81             0.071429
y82             0.071429
y83             0.071429
y84             0.071429
y85             0.071429
y86             0.071429
y87             0.071429
y88             0.071429
y89             0.071429
y90             0.071429
y91             0.071429
y92             0.071429
y93             0.071429
ag0_14          0.223665
ag15_17         0.045864
ag18_24         0.116925
ag25_34         0.170531
incpc       14781.810422
polpc         267.807999
gincpc          0.059669
gpolpc          0.008005
cag0_14        -0.000898
cag15_17       -0.001100
cag18_24       -0.002448
cag25_34       -0.000262
cunem           0.000525
cblack          0.030098
cmetro          0.001596
pris          199.980341
lpris           5.129948
gpris           0.066474
final1          0.008403
final2          0.016807
final3          0.000000
dtype: float64

In [31]:
df.year.ffill()

0      80
1      81
2      82
3      83
4      84
       ..
709    89
710    90
711    91
712    92
713    93
Name: year, Length: 714, dtype: int64

In [32]:
df.year.bfill()

0      80
1      81
2      82
3      83
4      84
       ..
709    89
710    90
711    91
712    92
713    93
Name: year, Length: 714, dtype: int64

In [33]:
df.dtypes

rownames      int64
state         int64
year          int64
govelec       int64
black       float64
metro       float64
unem        float64
criv        float64
crip        float64
lcriv       float64
lcrip       float64
gcriv       float64
gcrip       float64
y81           int64
y82           int64
y83           int64
y84           int64
y85           int64
y86           int64
y87           int64
y88           int64
y89           int64
y90           int64
y91           int64
y92           int64
y93           int64
ag0_14      float64
ag15_17     float64
ag18_24     float64
ag25_34     float64
incpc       float64
polpc       float64
gincpc      float64
gpolpc      float64
cag0_14     float64
cag15_17    float64
cag18_24    float64
cag25_34    float64
cunem       float64
cblack      float64
cmetro      float64
pris        float64
lpris       float64
gpris       float64
final1        int64
final2        int64
final3      float64
dtype: object

In [34]:
df.shape

(714, 47)

In [36]:
df.isnull().any()

rownames    False
state       False
year        False
govelec     False
black       False
metro       False
unem        False
criv        False
crip        False
lcriv       False
lcrip       False
gcriv       False
gcrip       False
y81         False
y82         False
y83         False
y84         False
y85         False
y86         False
y87         False
y88         False
y89         False
y90         False
y91         False
y92         False
y93         False
ag0_14      False
ag15_17     False
ag18_24     False
ag25_34     False
incpc       False
polpc       False
gincpc      False
gpolpc      False
cag0_14     False
cag15_17    False
cag18_24    False
cag25_34    False
cunem       False
cblack      False
cmetro      False
pris        False
lpris       False
gpris       False
final1      False
final2      False
final3       True
dtype: bool

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 47 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  714 non-null    int64
 1   state     714 non-null    int64
 2   year      714 non-null    int64
 3   govelec   714 non-null    int64
 4   black     714 non-null    float64
 5   metro     714 non-null    float64
 6   unem      714 non-null    float64
 7   criv      714 non-null    float64
 8   crip      714 non-null    float64
 9   lcriv     714 non-null    float64
 10  lcrip     714 non-null    float64
 11  gcriv     714 non-null    float64
 12  gcrip     714 non-null    float64
 13  y81       714 non-null    int64
 14  y82       714 non-null    int64
 15  y83       714 non-null    int64
 16  y84       714 non-null    int64
 17  y85       714 non-null    int64
 18  y86       714 non-null    int64
 19  y87       714 non-null    int64
 20  y88       714 non-null    int64
 21  y89       714 non-null    int64
 22  y90       714 non-null    int64
 23  y91       714 non-null    int64
 24  y92       714 non-null    int64
 25  y93       714 non-null    int64
 26  ag0_14    714 non-null    float64
 27  ag15_17   714 non-null    float64
 28  ag18_24   714 non-null    float64
 29  ag25_34   714 non-null    float64
 30  incpc     714 non-null    float64
 31  polpc     714 non-null    float64
 32  gincpc    714 non-null    float64
 33  gpolpc    714 non-null    float64
 34  cag0_14   714 non-null    float64
 35  cag15_17  714 non-null    float64
 36  cag18_24  714 non-null    float64
 37  cag25_34  714 non-null    float64
 38  cunem     714 non-null    float64
 39  cblack    714 non-null    float64
 40  cmetro    714 non-null    float64
 41  pris      714 non-null    float64
 42  lpris     714 non-null    float64
 43  gpris     714 non-null    float64
 44  final1    714 non-null    int64
 45  final2    714 non-null    int64
 46  final3    0 non-null      float64
dtypes: float64(28), int64(19)
memory usage: 262.3 KB

In [37]:
df['black'].mean()

0.10532941171411599

In [39]:
df['black'].median()

0.0710000023245811

In [41]:
df['year'].mode()

0     80
1     81
2     82
3     83
4     84
5     85
6     86
7     87
8     88
9     89
10    90
11    91
12    92
13    93
Name: year, dtype: int64

In [47]:
newcrip = df["crip"]
newcrip[np.abs(newcrip) > 40]

0      44.476376
1      44.248787
2      42.050446
8      41.055916
9      41.251614
         ...
701    47.018291
702    44.642292
706    41.542339
711    40.965065
712    42.647312
Name: crip, Length: 500, dtype: float64

In [54]:
df[np.abs(newcrip) > 80]

,rownames,state,year,govelec,black,metro,unem,criv,crip,lcriv,...,cag18_24,cag25_34,cunem,cblack,cmetro,pris,lpris,gpris,final1,final2
112,113,9,80,1,0.7030,1.0,0.07400,20.755486,81.164574,3.032811,...,-0.001809,0.005098,-0.00217,-0.079994,0.0,399.846161,5.991080,0.049722,0,0
113,114,9,81,0,0.6985,1.0,0.08867,23.618525,85.549454,3.162031,...,-0.001331,0.008152,0.01467,-0.450005,0.0,426.175537,6.054852,0.063772,0,0
114,115,9,82,0,0.6940,1.0,0.10417,21.916405,83.582016,3.087235,...,-0.000864,0.005683,0.01550,-0.449997,0.0,460.282562,6.131841,0.076989,0,0
122,123,9,90,0,0.6580,1.0,0.06733,24.700331,83.559601,3.206817,...,0.002749,-0.004797,0.01658,-0.449997,0.0,1065.705078,6.971392,0.012883,0,0
123,124,9,91,0,0.6535,1.0,0.07700,24.698652,83.707069,3.206749,...,-0.007815,0.000006,0.00967,-0.450005,0.0,1125.496704,7.025980,0.054588,0,0
124,125,9,92,1,0.6490,1.0,0.08400,28.521368,86.328209,3.350654,...,-0.008288,0.001373,0.00700,-0.449997,0.0,1196.296265,7.086986,0.061006,0,0
125,126,9,93,0,0.6445,1.0,0.08500,29.217993,88.392731,3.374785,...,-0.008931,-0.001017,0.00100,-0.450005,0.0,1286.837524,7.159943,0.072958,0,0